#!/bin/sh
#
###############################################################################
# This file is part of "Patrick's Programming Library", Version 7 (PPL7).
# Web: http://www.pfp.de/ppl/
#
# $Author$
# $Revision$
# $Date$
# $Id$
#
###############################################################################
#
# Copyright (c) 2013, Patrick Fedick <patrick@pfp.de>
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#   1. Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer. 
#   2. Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution. 
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
###############################################################################

ACLOCAL=aclocal
AUTOMAKE=automake
AUTOCONF=autoconf




cat WinMusik.pro.header > WinMusik.pro.in
(
	echo ""
	echo -n "SOURCES += "
	filelist=`find src widgets pplib/ppl6 -name '*.cpp'`
	for file in $filelist; do
		echo "$file \\"
		echo -n "    "
	done
	echo ""
	echo ""
	echo -n "HEADERS += "
	filelist=`find widgets src include pplib/include -name '*.h'`
	for file in $filelist; do
		echo "$file \\"
		echo -n "    "
	done
	echo ""
	echo ""
	echo -n "FORMS += "
	filelist=`find widgets src forms -name '*.ui'`
	for file in $filelist; do
		echo "$file \\"
		echo -n "    "
	done
	echo ""	
) >>  WinMusik.pro.in


$ACLOCAL
$AUTOMAKE --add-missing
$AUTOCONF

