#!/bin/sh
###############################################################################
# This file is part of WinMusik 3 by Patrick Fedick                           #
# Web: https://www.pfp.de/winmusik/                                           #
###############################################################################
#
# Copyright (c) 2022, Patrick Fedick <patrick@pfp.de>
# All rights reserved.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

ACLOCAL=aclocal
AUTOMAKE=automake
AUTOCONF=autoconf



cd gui
cat WinMusik.pro.header > WinMusik.pro.in
(
	echo ""
	echo -n "SOURCES += "
	filelist=`find src widgets -name '*.cpp'`
	for file in $filelist; do
		echo "$file \\"
		echo -n "    "
	done
	echo ""
	echo ""
	echo -n "HEADERS += "
	filelist=`find widgets src include -name '*.h'`
	for file in $filelist; do
		echo "$file \\"
		echo -n "    "
	done
	echo ""
	echo ""
	echo -n "FORMS += "
	filelist=`find widgets src forms -name '*.ui'`
	for file in $filelist; do
		echo "$file \\"
		echo -n "    "
	done
	echo ""	
) >>  WinMusik.pro.in
cd ..


$ACLOCAL
$AUTOMAKE --add-missing --copy
$AUTOCONF

