name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          #fetch-depth: 0
      - name: Install Dependencies
        run: sudo apt install -y qt6-base-dev qt6-base-dev-tools dpkg-dev libcdio-dev zlib1g-dev libbz2-dev libpng-dev libpcre2-dev libcurl4-openssl-dev
      - name: configure
        run: ./configure
      - name: make
        run: make
