name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: apt install -y qt5-default qt5-qmake dpkg-dev libcdio-dev zlib1g-dev libbz2-dev libpng-dev libpcre3-dev
      - name: configure
        run: ./configure
      - name: make
        run: make

